foreground #ffffff
background #242424
cursor #389efc
selection_foreground #0d1117
selection_background #58a6ff


#: Cursor colors

cursor #58a6ff


#: Tab bar colors

tab_bar_background #010409
active_tab_foreground #c9d1d9
active_tab_background #0d1117
inactive_tab_foreground #8b949e
inactive_tab_background #010409


#: The basic 16 colors

#: black
color0 #484f58
color8 #6e7681

#: red
color1 #a85fed
color9 #bf5ec4

#: green
color2 #4bc9bf
color10 #56d38e

#: yellow
color3 #8ec963
color11 #b6cc5c

#: blue
color4 #58a6ff
color12 #79c0ff

#: magenta
color5 #8c8eff
color13 #d2a8ff

#: cyan
color6 #39c5cf
color14 #56d4dd

#: white
color7 #b1bac4
color15 #ffffff
